#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     llauncher,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     left2,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lifter,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rlauncher,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     right2,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Team 7347 Nick Vosseteig
//Could not get to work correctly
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
float rightWheelRevolutionsTraveled(){
		return (nMotorEncoder[right2]/1439.7);
}
float leftWheelRevolutionsTraveled(){
		return (nMotorEncoder[left2]/37.6);
}
task main()
{
  initializeRobot();



  waitForStart(); // Wait for the beginning of autonomous phase.
  //nMotorEncoder[right2] = 0;
  //nMotorEncoder[left2] = 0;
  //int motorStartingTicks = nMotorEncoder[right2];
  //motor[left] = 100;
  //motor[right] = 100;
  //motor[left2] = 100;
  //motor[right2] = 100;
  //  while (nMotorEncoder[right2] < 1440000) {
		//nxtDisplayCenteredTextLine(2, "renc: %d, %d", nMotorEncoder[right2]/1439.7);
		//	nxtDisplayCenteredTextLine(3, "lenc: %d, %d", nMotorEncoder[left2]/37.6);
		//	nxtDisplayCenteredTextLine(4, "R/L: %d", (rightWheelRevolutionsTraveled())/(leftWheelRevolutionsTraveled());
		//	nxtDisplayCenteredTextLine(5, "R revs: %d", (rightWheelRevolutionsTraveled());
		//	nxtDisplayCenteredTextLine(6, "L revs: %d", (leftWheelRevolutionsTraveled());
  //}
  //R 14397, L 376 motor turned 10 times
  //motor[left] = 0;
  //motor[right] = 0;
  //motor[left2] = 0;
  //motor[right2] = 0;

  nMotorEncoder[llauncher] = 0;
  nMotorEncoder[rlauncher] = 0;
 	motor[llauncher] = 127;
 	motor[rlauncher] = 127;
  while (true) {
		nxtDisplayCenteredTextLine(2, "renc: %d, %d", nMotorEncoder[llauncher]);
			nxtDisplayCenteredTextLine(3, "lenc: %d, %d", nMotorEncoder[rlauncher]);
			nxtDisplayCenteredTextLine(4, "R/L: %d", ((float)nMotorEncoder[rlauncher])/((float)nMotorEncoder[llauncher]));
  }
  motor[llauncher] = 0;
  motor[rlauncher] = 0;

}
