#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     spinner2,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	while(true)
	{
		//each stick controls a motor
		getJoystickSettings(joystick);

		if(joystick.joy1_y1<20 && joystick.joy1_y1>-20){
			motor[left] = 0;
			motor[left2] = 0;
			}else{
			motor[left] = -joystick.joy1_y1/2;
			motor[left2] = joystick.joy1_y1/2;
		}
		if(joystick.joy1_y2<20 && joystick.joy1_y2>-20){
			motor[right] = 0;
			motor[right2] = 0;
			}else{
			motor[right] = joystick.joy1_y2/2;
			motor[right2] = joystick.joy1_y2/2;
		}
		if(joy1Btn(2)){
			motor[spinner2] = 100;
			}else if(joy1Btn(1)){
			motor[spinner2] = -100;
			}else{
			motor[spinner2] = 0;
		}
		if(joy1Btn(3)){
			motor[spinner] = 100;
			}else if(joy1Btn(4)){
			motor[spinner] = -100;
			}else{
			motor[spinner] = 0;
		}
	}
}
