#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     lifter,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rlauncher,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     right2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     llauncher,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    opener,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Team 7347, Nick Vosseteig, Alex Iverson

#include "JoystickDriver.c"

const int driveType = 1;

task main()
{
	while(true)
	{
		//each stick controls a motor
		getJoystickSettings(joystick);

		if (driveType == 0) {

			if(joystick.joy1_y1<20 && joystick.joy1_y1>-20){
				motor[left] = 0;
				motor[left2] = 0;
				}else{
				motor[left] = -joystick.joy1_y1;
				motor[left2] = joystick.joy1_y1;
			}
			if(joystick.joy1_y2<20 && joystick.joy1_y2>-20){
				motor[right] = 0;
				motor[right2] = 0;
				}else{
				motor[right] = joystick.joy1_y2;
				motor[right2] = joystick.joy1_y2;
			}
			} else if (driveType == 1) {
			int leftIn = joystick.joy1_y1;
			int leftPwr = leftIn * leftIn / 127;
			if (leftIn < 0) {
				leftPwr = leftPwr * -1;
			}
			motor[left] = -leftPwr;
			motor[left2] = leftPwr;
			int rightIn = joystick.joy1_y2;
			int rightPwr = rightIn * rightIn / 127;
			if (rightIn < 0) {
				rightPwr = rightPwr * -1;
			}
			motor[right] = rightPwr;
			motor[right2] = rightPwr;
		}
		if(joy1Btn(6)){
			motor[intake] = -100;
			motor[llauncher] = -127;
			motor[rlauncher] = -127;
			}else if(joy1Btn(8)){
			motor[intake] = 100;
			motor[llauncher] = 127;
			motor[rlauncher] = 127;
			}else{
			motor[intake] = 0;
			motor[llauncher] = 0;
			motor[rlauncher] = 0;
		}
		if(joy1Btn(2)){
			servo[grabber] = 0;
		}else if(joy1Btn(1)){
			servo[grabber] = 85;
		}
		if(joy1Btn(3)){
			servo[opener] = 0;
		}else if(joy1Btn(4)){
			servo[opener] = 188;
		}
		//added jan 7
		if(joy1Btn(5)){
			motor[lifter] = 100;
		}else if(joy1Btn(7)){
			motor[lifter] = -100;
		}
		else{
			motor[lifter] = 0;
		}
	}
}
