#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left2,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     llifter,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rlifter,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     right2,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     launcher,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    opener,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "PID.h"
#include "JoystickDriver.c"

PIDController pid = {
	1,0,0,0,0,0,0,0,0,0, false, 0};

task main()
{
	pid.kP = 0.1;
	waitForStart();
	nMotorEncoder[left2] = 0;
	nMotorEncoder[right2] = 0;
	while(nMotorEncoder[left2] <= 14400) {
		float pwr = 100;
		float steer = PIDUpdate(nMotorEncoder[left2] - nMotorEncoder[right2], &pid);
		motor[left] = pwr + steer;
		motor[left2] = pwr + steer;
		motor[right] = pwr - steer;
		motor[right2] = pwr - steer;
		wait1Msec(20);
	}
	motor[left] = 0;
	motor[left2] = 0;
	motor[right] = 0;
	motor[right2] = 0;

}
