#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     test,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     test2,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int LaunchEncoderValue = 0;
int EncoderReadTime = 0;
float LauncherAngularVelocity = 0;

void UpdateEncoders(){
	EncoderReadTime = time1[T1];
	LaunchEncoderValue = nMotorEncoder[test];
	LauncherAngularVelocity = ((float)LaunchEncoderValue/(float)EncoderReadTime);
	nMotorEncoder[test] = 0;
	ClearTimer(T1);
}
task main()
{
	nMotorEncoder[test] = 0;
	while(true)
	{
		//1230
		getJoystickSettings(joystick);

		nxtDisplayCenteredTextLine(2, "enc: %d",nMotorEncoder[test]);
		nxtDisplayCenteredTextLine(3, "AngVel: %f", LauncherAngularVelocity);
		nxtDisplayCenteredTextLine(1, "time: %f", time10[T2]);
		if(time1[T1]>200){
			UpdateEncoders();
		}

		if(joy1Btn(2)&& time10(T2)>100 && LauncherAngularVelocity > 1){
			motor[test] = 127;
			motor[test2] = -127;
			}else if(joy1Btn(1)&& time10(T2)>100 && LauncherAngularVelocity > 1){
			motor[test] = -127;
			motor[test2] = 127;
			}else{
			if(joystick.joy1_y2<20 && joystick.joy1_y2>-20){
				motor[test] = 0;
				ClearTimer(T2);
				}else{
				motor[test] = joystick.joy1_y2;
			}

			if(joystick.joy1_y2<20 && joystick.joy1_y2>-20){
				motor[test2] = 0;
				ClearTimer(T2);
				}else{
				motor[test2] = joystick.joy1_y2;
			}
		}

		if(joy1Btn(3)){
			motor[test] = 127;
			motor[test2] = -127;
			}else if(joy1Btn(4)){
			motor[test] = -127;
			motor[test2] = 127;
		}
	}
}
