#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     left2,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     llifter,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rlifter,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     right2,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     launcher,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    opener,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "PID.h"

void drive(int speed) {
	motor[left] = speed;
	motor[right] = speed;
	motor[left2] = speed;
	motor[right2] = speed;
}

PIDController pid = {
	1,0,0,0,0,0,0,0,0,0, false, 0};

task main() {
	pid.setPoint = 90;
	pid.kP = 0.1;
	pid.minOutput = -127;
	pid.maxOutput = 127;
	while (true) {
		float pwr = PIDUpdate(nMotorEncoder[left2], &pid);
		nxtDisplayCenteredTextLine(1, "encoder: %d", nMotorEncoder[left2]);
		nxtDisplayCenteredTextLine(2, "motor: %d", pwr);
		motor[left2] = pwr;
		wait1Msec(20);
	}
}
